
set(MARVEL_SOURCES

	"$<$<PLATFORM_ID:Windows>:src/core/Modules/mvModule_Core.cpp>"
	"$<$<PLATFORM_ID:Linux>:src/core/Modules/mvModule_Core.cpp>"
	"$<$<PLATFORM_ID:Darwin>:src/core/Modules/mvModule_Core.mm>"

	"src/core/AppItems/composite/mvDebugWindow.cpp"
	"src/core/AppItems/composite/mvDocWindow.cpp"

	"src/core/PythonUtilities/mvPyObject.cpp"
	"src/core/PythonUtilities/mvPythonTranslator.cpp"
	"src/core/PythonUtilities/mvPythonParser.cpp"
	"src/core/PythonUtilities/mvPythonExceptions.cpp"
	"src/core/PythonUtilities/mvGlobalIntepreterLock.cpp"
	"src/core/PythonUtilities/mvPythonTypeChecker.cpp"

	"$<$<PLATFORM_ID:Windows>:src/platform/Windows/mvWindowsViewport.cpp>"
	"$<$<PLATFORM_ID:Windows>:src/platform/Windows/mvUtilities.cpp>"

	"$<$<PLATFORM_ID:Darwin>:src/platform/Apple/mvAppleViewport.mm>"
	"$<$<PLATFORM_ID:Darwin>:src/platform/Apple/mvAppleUtilities.mm>"

	"$<$<PLATFORM_ID:Linux>:src/platform/Linux/mvUtilities.cpp>"
	"$<$<PLATFORM_ID:Linux>:src/platform/Linux/mvLinuxViewport.cpp>"

	"src/core/mvEvents.cpp"
	"src/core/mvApp.cpp"
	"src/core/mvAppLog.cpp"
	"src/core/mvInput.cpp"
	"src/core/mvViewport.cpp"
	"src/core/mvProfiler.cpp"
	"src/core/mvLog.cpp"

	"src/core/CustomImGuiWidgets/mvKnobCustom.cpp"
	"src/core/CustomImGuiWidgets/mvLoadingIndicatorCustom.cpp"

	"src/core/Theming/mvThemeManager.cpp"
	"src/core/Theming/mvFontScope.cpp"
	"src/core/Theming/mvFontManager.cpp"

	"src/core/Registries/mvCallbackRegistry.cpp"
	"src/core/Registries/mvTextureStorage.cpp"

	"src/core/AppItems/mvAppItemState.cpp"
	"src/core/AppItems/mvAppItem.cpp"
	"src/core/AppItems/mvTypeBases.cpp"
	"src/core/AppItems/mvItemRegistry.cpp"

	"src/core/AppItems/basic/mvMenuItem.cpp"
	"src/core/AppItems/basic/mvInputText.cpp"
	"src/core/AppItems/basic/mvText.cpp"
	"src/core/AppItems/basic/mvSliderSingle.cpp"
	"src/core/AppItems/basic/mvSliderMulti.cpp"
	"src/core/AppItems/basic/mvImage.cpp"
	"src/core/AppItems/basic/mvImageButton.cpp"
	"src/core/AppItems/basic/mvColorButton.cpp"
	"src/core/AppItems/basic/mvColorEdit.cpp"
	"src/core/AppItems/basic/mvColorPicker.cpp"
	"src/core/AppItems/basic/mvRadioButton.cpp"
	"src/core/AppItems/basic/mvListbox.cpp"
	"src/core/AppItems/basic/mvCombo.cpp"
	"src/core/AppItems/basic/mvCheckbox.cpp"
	"src/core/AppItems/basic/mvButton.cpp"
	"src/core/AppItems/basic/mvSelectable.cpp"
	"src/core/AppItems/basic/mvTabButton.cpp"
	"src/core/AppItems/basic/mvDragSingle.cpp"
	"src/core/AppItems/basic/mvDragMulti.cpp"
	"src/core/AppItems/basic/mvInputSingle.cpp"
	"src/core/AppItems/basic/mvInputMulti.cpp"

	"src/core/AppItems/misc/mvProgressBar.cpp"
	"src/core/AppItems/misc/mvSameLine.cpp"
	"src/core/AppItems/misc/mvSeparator.cpp"
	"src/core/AppItems/misc/mvDummy.cpp"
	"src/core/AppItems/misc/mvSpacing.cpp"

	"src/core/AppItems/containers/mvCollapsingHeader.cpp"
	"src/core/AppItems/containers/mvGroup.cpp"
	"src/core/AppItems/containers/mvChild.cpp"
	"src/core/AppItems/containers/mvTooltip.cpp"
	"src/core/AppItems/containers/mvTab.cpp"
	"src/core/AppItems/containers/mvTabBar.cpp"
	"src/core/AppItems/containers/mvMenu.cpp"
	"src/core/AppItems/containers/mvMenuBar.cpp"
	"src/core/AppItems/containers/mvTreeNode.cpp"
	"src/core/AppItems/containers/mvWindowAppItem.cpp"
	"src/core/AppItems/containers/mvPopup.cpp"

	"src/core/AppItems/tables/mvTable.cpp"
	"src/core/AppItems/tables/mvTableColumn.cpp"
	"src/core/AppItems/tables/mvTableNextColumn.cpp"

	"src/core/AppItems/custom/mvDatePicker.cpp"
	"src/core/AppItems/custom/mvTimePicker.cpp"
	"src/core/AppItems/custom/mvTextEditor.cpp"
	"src/core/AppItems/custom/mvColorMapScale.cpp"
	"src/core/AppItems/custom/mvSlider3D.cpp"
	"src/core/AppItems/custom/mvKnob.cpp"
	"src/core/AppItems/custom/mvLoadingIndicator.cpp"

	"src/core/AppItems/drawing/mvDrawing.cpp"
	"src/core/AppItems/drawing/mvDrawLine.cpp"
	"src/core/AppItems/drawing/mvDrawArrow.cpp"
	"src/core/AppItems/drawing/mvDrawTriangle.cpp"
	"src/core/AppItems/drawing/mvDrawCircle.cpp"
	"src/core/AppItems/drawing/mvDrawBezierCurve.cpp"
	"src/core/AppItems/drawing/mvDrawQuad.cpp"
	"src/core/AppItems/drawing/mvDrawRect.cpp"
	"src/core/AppItems/drawing/mvDrawText.cpp"
	"src/core/AppItems/drawing/mvDrawPolygon.cpp"
	"src/core/AppItems/drawing/mvDrawPolyline.cpp"
	"src/core/AppItems/drawing/mvDrawImage.cpp"
	
	"src/core/AppItems/composite/mvFileDialog.cpp"
	"src/core/AppItems/composite/mvAboutWindow.cpp"
	"src/core/AppItems/composite/mvDataGrid.cpp"
	"src/core/AppItems/composite/mvLogger.cpp"
	"src/core/AppItems/composite/mvStyleWindow.cpp"
	"src/core/AppItems/composite/mvMetricsWindow.cpp"
	"src/core/AppItems/composite/mvAboutWindow.cpp"

	"src/core/AppItems/nodes/mvNodeEditor.cpp"
	"src/core/AppItems/nodes/mvNode.cpp"
	"src/core/AppItems/nodes/mvNodeAttribute.cpp"
	
	"src/core/AppItems/plots/mvPlot.cpp"
	"src/core/AppItems/plots/mvAreaSeries.cpp"
	"src/core/AppItems/plots/mvDragPoint.cpp"
	"src/core/AppItems/plots/mvDragLine.cpp"
	"src/core/AppItems/plots/mvAnnotation.cpp"
	"src/core/AppItems/plots/mvSimplePlot.cpp"
	"src/core/AppItems/plots/mvLineSeries.cpp"
	"src/core/AppItems/plots/mvScatterSeries.cpp"
	"src/core/AppItems/plots/mvStemSeries.cpp"
	"src/core/AppItems/plots/mvStairSeries.cpp"
	"src/core/AppItems/plots/mvBarSeries.cpp"
	"src/core/AppItems/plots/mvErrorSeries.cpp"
	"src/core/AppItems/plots/mvInfiniteLineSeries.cpp"
	"src/core/AppItems/plots/mvHeatSeries.cpp"
	"src/core/AppItems/plots/mvImageSeries.cpp"
	"src/core/AppItems/plots/mvPieSeries.cpp"
	"src/core/AppItems/plots/mvShadeSeries.cpp"
	"src/core/AppItems/plots/mvLabelSeries.cpp"
	"src/core/AppItems/plots/mvCandleSeries.cpp"

	# imnodes
	"vendor/imnodes/imnodes.cpp"

	# implot
	"vendor/implot/implot.cpp"
	"vendor/implot/implot_items.cpp"
	"vendor/implot/implot_demo.cpp"

	# ImGuiFileDialog
	"../Dependencies/ImGuiFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp"

	# imgui
	"../Dependencies/imgui/misc/freetype/imgui_freetype.cpp"
	"../Dependencies/imgui/misc/cpp/imgui_stdlib.cpp"
	"../Dependencies/imgui/imgui.cpp"
	"../Dependencies/imgui/imgui_demo.cpp"
	"../Dependencies/imgui/imgui_draw.cpp"
	"../Dependencies/imgui/imgui_widgets.cpp"
	"../Dependencies/imgui/imgui_tables.cpp"
	"$<$<PLATFORM_ID:Windows>:../Dependencies/imgui/backends/imgui_impl_win32.cpp>"
	"$<$<PLATFORM_ID:Windows>:../Dependencies/imgui/backends/imgui_impl_dx11.cpp>"
	"$<$<PLATFORM_ID:Darwin>:../Dependencies/imgui/backends/imgui_impl_metal.mm>"
	"$<$<PLATFORM_ID:Darwin>:../Dependencies/imgui/backends/imgui_impl_glfw.cpp>"
	"$<$<PLATFORM_ID:Linux>:../Dependencies/imgui/examples/libs/gl3w/GL/gl3w.c>"
	"$<$<PLATFORM_ID:Linux>:../Dependencies/imgui/backends/imgui_impl_glfw.cpp>"
	"$<$<PLATFORM_ID:Linux>:../Dependencies/imgui/backends/imgui_impl_opengl3.cpp>"
)

set(MARVEL_INCLUDE_DIR

	"vendor/implot"
	"vendor/stb"
	"vendor/imnodes"
	"src/"
	"src/core"
	"src/core/CustomImGuiWidgets"
	"src/core/Modules"
	"src/core/AppItems"
	"src/core/DrawCommands"
	"src/core/CppUtilities"
	"src/core/PythonUtilities"
	"src/core/Registries"
	"src/core/Theming"
	"$<$<PLATFORM_ID:Windows>:${CMAKE_SOURCE_DIR}/DearPyGui/vendor/dirent/>"
	"../Dependencies/ImGuiFileDialog/ImGuiFileDialog/"
	"../Dependencies/spdlog/include/"
	"../Dependencies/glfw/include/"
	"../Dependencies/glfw/deps/"
	"../Dependencies/imgui/"
	"../Dependencies/imgui/misc/freetype/"
	"../Dependencies/imgui/backends/"
	"../Dependencies/imgui/examples/libs/gl3w"
	"../Dependencies/cpython/"
	"../Dependencies/cpython/Include/"
	"$<$<PLATFORM_ID:Windows>:${CMAKE_SOURCE_DIR}/Dependencies/cpython/PC/>"
	# may can delete this
	"../Dependencies/cpython/debug/"
)
