#pragma once

#include "core/AppItems/basic/mvInputText.h"
#include "core/AppItems/basic/mvBasicItems.h"
#include "core/AppItems/basic/mvInputItems.h"
#include "core/AppItems/basic/mvSliderItems.h"
#include "core/AppItems/basic/mvDragItems.h"
#include "core/AppItems/basic/mvMiscItems.h"
#include "core/AppItems/basic/mvColorItems.h"
#include "core/AppItems/basic/mvText.h"
#include "core/AppItems/basic/mvImage.h"

#include "core/AppItems/containers/mvContainerItems.h"
#include "core/AppItems/containers/mvTab.h"
#include "core/AppItems/containers/mvMenu.h"
#include "core/AppItems/containers/mvTooltip.h"
#include "core/AppItems/containers/mvColumns.h"
#include "core/AppItems/containers/mvWindowAppItem.h"
#include "core/AppItems/containers/mvPopup.h"

#include "core/AppItems/custom/mvDrawing.h"
#include "core/AppItems/custom/mvTimePicker.h"
#include "core/AppItems/custom/mvDatePicker.h"

#include "core/AppItems/composite/mvTable.h"
#include "core/AppItems/composite/mvLogger.h"
#include "core/AppItems/composite/mvAboutWindow.h"
#include "core/AppItems/composite/mvDocWindow.h"
#include "core/AppItems/composite/mvDebugWindow.h"
#include "core/AppItems/composite/mvMetricsWindow.h"
#include "core/AppItems/composite/mvStyleWindow.h"
#include "core/AppItems/composite/mvFileDialog.h"

#include "core/AppItems/plots/mvPlot.h"
#include "core/AppItems/plots/mvSimplePlot.h"
#include "core/AppItems/plots/mvLineSeries.h"
#include "core/AppItems/plots/mvBarSeries.h"
#include "core/AppItems/plots/mvScatterSeries.h"
#include "core/AppItems/plots/mvAreaSeries.h"
#include "core/AppItems/plots/mvStemSeries.h"
#include "core/AppItems/plots/mvLabelSeries.h"
#include "core/AppItems/plots/mvPieSeries.h"
#include "core/AppItems/plots/mvShadeSeries.h"
#include "core/AppItems/plots/mvErrorSeries.h"
#include "core/AppItems/plots/mvHeatSeries.h"
#include "core/AppItems/plots/mvImageSeries.h"
#include "core/AppItems/plots/mvStairSeries.h"
#include "core/AppItems/plots/mvCandleSeries.h"
